In [123]:
import numpy as np

In [124]:
class Neuron():
    def __init__(self, ninputs):
        self._weights = np.random.randn(ninputs) * 0.01
        self._bias = np.random.randn() * 0.01
    
    def predict(self, X):
        x = np.atleast_2d(X)
        return x @ self._weights + self._bias
    
    def error(self, X, y):
        yp = self.predict(X)
        e = 0.5 * (y - yp) ** 2
        return e
    
    def delta(self, X, y, w):
        yp = self.predict(X)
        return (y - yp)
    
    def fit(self, X, y, lr=0.01):
        yp = self.predict(X)
        e = y - yp
        self._weights += lr * X * e
        self._bias += lr * e

In [125]:
class Layer():
    def __init__(self, ninputs, noutputs):
        self._neurons = [Neuron(ninputs) for _ in range(noutputs)]
    
    def predict(self, X):
        return np.array([n.predict(X) for n in self._neurons])
    
    def fit(self, X, y, lr=0.01):
        for neuron, yv in zip(self._neurons, y):
            neuron.fit(X, yv, lr=lr)
    
    @property
    def weights(self):
        wts = np.array([n._weights for n in self._neurons])
        biases = np.array([n._bias for n in self._neurons])
        biases = biases.reshape((-1, 1))
        return np.hstack([wts, biases])

In [126]:
l = Layer(2, 4)

In [127]:
l.predict(np.arange(2))

array([[0.00567237],
       [0.02865928],
       [0.01002749],
       [0.01142142]])

In [128]:
print(l.weights)

[[ 0.00579258  0.00398574  0.00168663]
 [ 0.0128448   0.01991593  0.00874334]
 [-0.00306464  0.00571358  0.00431391]
 [-0.02702576  0.01053737  0.00088405]]


In [129]:
l.fit(np.arange(2), np.arange(4))

In [130]:
print(l.weights)

[[ 0.00579258  0.00392901  0.00162991]
 [ 0.0128448   0.02962934  0.01845675]
 [-0.00306464  0.0256133   0.02421364]
 [-0.02702576  0.04042315  0.03076983]]


In [131]:
l.fit(np.arange(2), np.arange(4))
print(l.weights)

[[ 0.00579258  0.00387342  0.00157432]
 [ 0.0128448   0.03914848  0.02797589]
 [-0.00306464  0.04511503  0.04371537]
 [-0.02702576  0.06971122  0.0600579 ]]


In [132]:
for epoch in range(1000):
    l.fit(np.arange(2), np.arange(4))
print(l.weights)

[[ 5.79257762e-03  1.14955084e-03 -1.14955083e-03]
 [ 1.28448009e-02  5.05586294e-01  4.94413705e-01]
 [-3.06463732e-03  1.00069983e+00  9.99300166e-01]
 [-2.70257597e-02  1.50482666e+00  1.49517334e+00]]


In [133]:
for epoch in range(10000):
    l.fit(np.arange(2), np.arange(4))
print(l.weights)

[[ 5.79257762e-03  1.14955083e-03 -1.14955083e-03]
 [ 1.28448009e-02  5.05586295e-01  4.94413705e-01]
 [-3.06463732e-03  1.00069983e+00  9.99300168e-01]
 [-2.70257597e-02  1.50482666e+00  1.49517334e+00]]


In [134]:
for epoch in range(100000):
    l.fit(np.arange(2), np.arange(4))
print(l.weights)

[[ 5.79257762e-03  1.14955083e-03 -1.14955083e-03]
 [ 1.28448009e-02  5.05586295e-01  4.94413705e-01]
 [-3.06463732e-03  1.00069983e+00  9.99300168e-01]
 [-2.70257597e-02  1.50482666e+00  1.49517334e+00]]
